### ISSUE TITLE
[Enhancement] deb package details missing

### ISSUE THREAD

**Issue by torgeros** [jonasmusall/texpaste#16]
### Proposed Enhancement

The `.deb` package is missing a lot of details for the application. Install with a GUI therefore looks really sketchy.

![Screenshot from 2022-10-14 12-51-51](https://user-images.githubusercontent.com/67151313/195900917-88c4277a-a741-4fe2-a637-40cd2e0436e1.png)

**Comment by jonasmusall** [comment]
This seems to be a shortfall of the DEB format:

> For traditionally packaged applications, for example in RPM or DEB format, there is no safety or permissions information available and nothing can currently be done to add it to an application.

from https://gitlab.gnome.org/GNOME/gnome-software/-/wikis/software-metadata#user-content-how-to-fix-incorrect-safety-and-permissions-information

**Comment by jonasmusall** [comment]
However it might be possible to add at least a bit more information. A DEB file is an archive which contains the following:
```yml
texpaste_1.2.0_linux.deb:
  - control.tar.gz:
    - control # metadata, see below
    - md5sums
    - postinst # script for installation
    - postrm # script for removal
  - data.tar.gz: # actual application files
    - ...
  - debian-binary # DEB package version
```

Currently, the `deb/control.tar.gz/control` file has these contents:
```yml
Package: texpaste
Version: 1.2.0
License: GPL-3.0
Vendor: Jonas Musall
Architecture: amd64
Maintainer: Jonas Musall
Installed-Size: 271066
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
Recommends: libappindicator3-1
Section: default
Priority: optional
Homepage: https://github.com/jonasmusall/texpaste#readme
Description: 
  Live TeX rendering.
```

[This page](https://www.debian.org/doc/debian-policy/ch-controlfields.html) seems to list the possible fields, further investigation is needed if any of them can be added to improve the information displayed when opening the DEB package for installation.
